version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.ourbranch.com
          maxWaitForLoad: 60000

workflows:
  build:
    jobs:
      - lighthouse
