version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  test: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: "https://www.foo.software,https://www.foo.software/tag/articles/"
      - lighthouse-check/validate-status:
          minAccessibilityScore: "30"
          minBestPracticesScore: "30"
          minPerformanceScore: "30"
          minProgressiveWebAppScore: "30"
          minSeoScore: "30"
  test-foo: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          urls: $LIGHTHOUSE_CHECK_URLS
          tag: Orb
  test-foo-and-fail-if-bad: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          urls: $LIGHTHOUSE_CHECK_URLS
          tag: Orb
      - lighthouse-check/validate-status:
          minAccessibilityScore: "30"
          minBestPracticesScore: "30"
          minPerformanceScore: "30"
          minProgressiveWebAppScore: "30"
          minSeoScore: "30"
  test-config: 
    executor: lighthouse-check/default
    steps:
      - checkout
      - lighthouse-check/audit:
          configFile: ./test/config.json
  test-extra-headers: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: "https://lighthouse-check-action.now.sh/"
          extraHeaders: '{ \"x-test-1\": \"hello\", \"x-test-2\": \"world\" }'

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master
  test-foo:
    jobs:
      - test-foo:
          filters:
            branches:
              only: master
  test-foo-and-fail-if-bad:
    jobs:
      - test-foo-and-fail-if-bad:
          filters:
            branches:
              only: master
  test-config:
    jobs:
      - test-config:
          filters:
            branches:
              only: master
  test-extra-headers:
    jobs:
      - test-extra-headers:
          filters:
            branches:
              only: master
