version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  test: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.foo.software,https://www.foo.software/contact
      - lighthouse-check/validate-status:
          minAccessibilityScore: "30"
          minBestPracticesScore: "30"
          minPerformanceScore: "30"
          minProgressiveWebAppScore: "30"
          minSeoScore: "30"
      - lighthouse-check/audit:
          urls: $LIGHTHOUSE_CHECK_URLS
          tag: Orb

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master
