version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.ourbranch.com
workflows:
  version: 2
  build:
    jobs:
      - lighthouse
