version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - run: 
          name: Ping
          command: curl -v -L https://www.foo.software/ 2>&1 | egrep "^> (Host:|GET)"
      - lighthouse-check/audit:
          urls: https://www.ourbranch.com

workflows:
  build:
    jobs:
      - lighthouse
