version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  test:
    steps:
      - checkout

workflows:
  version: 2.1
  test:
    jobs:
      - lighthouse-check/audit:
          urls: https://www.foo.software,https://www.foo.software/contact
          # filters:
          #   branches:
          #     only: master
