version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

workflows:
  test:
    jobs:
      - lighthouse-check/audit:
          awsRegion: foobar
          urls: https://www.foo.software,https://www.foo.software/contact
          filters:
            branches:
              only: master
