version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@dev:alpha

jobs:
  test: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: "https://www.foo.software,https://www.foo.software/tag/articles/"
      - lighthouse-check/validate-status:
          minAccessibilityScore: "30"
          minBestPracticesScore: "30"
          minPerformanceScore: "30"
          minProgressiveWebAppScore: "30"
          minSeoScore: "30"
  test-automated-lighthouse-check: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          urls: $LIGHTHOUSE_CHECK_URLS
          tag: Orb
  test-automated-lighthouse-check-with-pr-comments: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          prCommentAccessToken: $LIGHTHOUSE_CHECK_ACCESS_TOKEN
          prCommentUrl: https://api.github.com/repos/foo-software/lighthouse-check-orb/pulls/$CIRCLE_PULL_REQUEST/reviews
          urls: $LIGHTHOUSE_CHECK_URLS
          tag: Orb

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master
  test-automated-lighthouse-check:
    jobs:
      - test-automated-lighthouse-check:
          filters:
            branches:
              only: master
  test-automated-lighthouse-check-with-pr-comments:
    jobs:
      - test-automated-lighthouse-check-with-pr-comments

